### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by jvanbaarsen** [orbitalimpact/opal-phaser#16]
First of all, awesome idea :D But I was wondering, against what version of Phaser is this project build? Also what is the state of the project? Would you consider it stable?

**Comment by ylluminarious** [comment]
Hi @jvanbaarsen. This project has been in development since late 2014, so it's compatible with versions of Phaser as far back as 2.2.0 and probably further. It is currently compatible with the most recent version of Phaser, 2.4.3. Normally, you'd be able to see it in action at our site (http://opalphaser.com) but it's currently down. However, we're working on getting it back up ASAP. Nonetheless, you can look at the various examples and games built with Phaser and see them running on versions like 2.4.3 or earlier.

Concerning whether the project is stable, I'd say yes. Various people (including myself) have built small games and examples with it, and it is even being used in a startup project. It should work for a lot of your Phaser needs, and contributions are always welcome if you want to add or improve features :)

**Comment by ylluminate** [comment]
@jvanbaarsen do you have any particular needs or usecases in mind at present? It's quite a nice effort so far and it's certainly got a future.  There has been discussion of even extending some Phaser game IDEs to work with `opal-phaser` or perhaps building our own.

**Comment by jvanbaarsen** [comment]
@ylluminate I don't have a really specific use case, but I'm considering this for some upcoming projects. Just wanted to make sure that I don't dive in and it turns out I'm working with phaser 1.x or something :smile:. Thanks for the quick response! This definitely answers my question :+1:
